# Generated by Django 5.1.3 on 2024-12-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='game',
        ),
    ]
